<form method="post" action="/login">
    <input type="text" name="login" placeholder="Логин" style="display: block">
    <input type="password" name="password" placeholder="Пароль" style="display: block">
    <div>Запомнить меня</div>
    <input style="display: inline" type="checkbox" name="remember" placeholder="Запомнить меня" value="true">
    <input type="submit" placeholder="Войти" style="display: block">
</form>